//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyousetsukaGetter.Localize.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SearchResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SearchResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SyousetsukaGetter.Localize.Resources.SearchResources", typeof(SearchResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_CancelBT {
            get {
                return ResourceManager.GetString("UI_CancelBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ジャンル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_GenreLabel {
            get {
                return ResourceManager.GetString("UI_GenreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_KeywordCheck {
            get {
                return ResourceManager.GetString("UI_KeywordCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nコード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_NcodeLabel {
            get {
                return ResourceManager.GetString("UI_NcodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力順序 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_OutputOrderLabel {
            get {
                return ResourceManager.GetString("UI_OutputOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リセット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_ResetBT {
            get {
                return ResourceManager.GetString("UI_ResetBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_SearchBT {
            get {
                return ResourceManager.GetString("UI_SearchBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索数（表示数） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_SearchNumLabel {
            get {
                return ResourceManager.GetString("UI_SearchNumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索単語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_SearchWordLabel {
            get {
                return ResourceManager.GetString("UI_SearchWordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   第二ジャンル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_SecondGenreLabel {
            get {
                return ResourceManager.GetString("UI_SecondGenreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あらすじ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_StoryCheck {
            get {
                return ResourceManager.GetString("UI_StoryCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイトル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_TitleCheck {
            get {
                return ResourceManager.GetString("UI_TitleCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_UserIDLabel {
            get {
                return ResourceManager.GetString("UI_UserIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作者名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_WriterCheck {
            get {
                return ResourceManager.GetString("UI_WriterCheck", resourceCulture);
            }
        }
    }
}
